### ISSUE TITLE
Unkown Error

### ISSUE THREAD

**Issue by blaggacao** [PowerShell/Win32-OpenSSH#74]
It never get's further than that:
```yaml
PS C:\Users\David> ssh -v 192.168.1.35
OpenSSH_7.1p1 Microsoft_Win32_port_with_VS, OpenSSL 1.0.2d 9 Jul 2015
debug1: Reading configuration data C:\Users\David/.ssh/config
debug1: Connecting to 192.168.1.35 [192.168.1.35] port 22.
debug1: allocating new sfd, sfd [3] fd [3] handle [664] type [2]
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: allocating new sfd, sfd [4] fd [4] handle [688] type [1]
debug1: identity file C:\Users\David\.ssh/id_rsa type 1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_rsa-cert type -1
debug1: allocating new sfd, sfd [4] fd [4] handle [116] type [1]
debug1: identity file C:\Users\David\.ssh/id_dsa type 2
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_dsa-cert type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_ecdsa type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_ecdsa-cert type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_ed25519 type -1
debug1: _open() returned error, errno [2]
debug1: key_load_public: No such file or directory
debug1: identity file C:\Users\David\.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.1p1 Microsoft_Win32_port_with_VS Dec 22 2015
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.1
debug1: match: OpenSSH_7.1 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.1.35:22 as 'David'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:M8oCm/7q7WkTRn/VliXaeUqr/5BdBvoXGZrfKLhmlEI
debug1: Host '192.168.1.35' is known and matches the ECDSA host key.
debug1: Found key in C:\Users\David\.ssh\known_hosts:29
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: Roaming not allowed by server
debug1: SSH2_MSG_SERVICE_REQUEST sent
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: allocating new sfd, sfd [4] fd [4] handle [684] type [2]
```

For now, can anybody help interpret this? It doesn't speak to me.
